version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: sg
      POSTGRES_USER: sg
      POSTGRES_PASSWORD: sg
